library(sqldf)
DF<- read.csv.sql("household_power_consumption.txt", header=T, sep=";", sql = 'select * from file where Date = "1/2/2007" or Date="2/2/2007"')
DF$Date<-as.Date(DF$Date,"%d/%m/%Y")
DF$Time<-strptime(paste(DF$Date,DF$Time),"%Y-%m-%d %H:%M:%S")
png(file="plot3.png",width = 480, height = 480, units = "px")
with(DF,plot(Time,Sub_metering_1,type="l",ylab="Energy sub metering",xlab="",col="black"))
with(DF,lines(Time,Sub_metering_2,type="l",col="red"))
with(DF,lines(Time,Sub_metering_3,type="l",col="blue"))
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
